name: Backend CI (Spring Boot + Maven)

on:
  push:
    branches: [ "**" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [ "**" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Package (skip tests for now)
        run: |
          if [ -f ./mvnw ]; then
            chmod +x ./mvnw
            ./mvnw -B -ntp -DskipTests package
          else
            mvn -B -ntp -DskipTests package
          fi

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar
          if-no-files-found: warn
